(()=>{
const $=x=>document.getElementById(x),bd=$('board'),tr=$('myHand'),g=$('guide'),st=$('status');
const rows={P:0,L:1,N:2,S:3,G:4,B:5,R:6,K:7,p:7,l:8,n:8,s:8,b:9,r:10},pr={P:'p',L:'l',N:'n',S:'s',B:'b',R:'r'};
const name={P:'歩',L:'香',N:'桂',S:'銀',G:'金',B:'角',R:'飛',K:'王',p:'と',l:'杏',n:'圭',s:'全',b:'馬',r:'龍'};
const mark=document.createElement('style');mark.textContent='.boardWrap{transform:none!important;margin-bottom:18px!important}.cell{overflow:hidden!important}.unit{width:92%!important;height:92%!important;animation:none!important}.tray{position:relative!important;z-index:20!important;margin-top:18px!important}.hand{background:#101b22!important;border-color:#b68b4e!important}.pieceTag{position:absolute;right:2px;bottom:2px;z-index:5;min-width:18px;padding:1px 3px;border:1px solid #f8d77a;border-radius:4px;background:#5d241eee;color:#fff7d5;font:700 11px serif;line-height:1;text-align:center;text-shadow:0 1px 1px #000;pointer-events:none}.pieceTag.enemy{left:2px;right:auto;top:2px;bottom:auto;background:#18385eee;border-color:#b8d9f8}.pieceTag.key{font-size:13px;padding:2px 4px;box-shadow:0 0 7px #ffe18a99}';document.head.append(mark);
let a=[],sel=-1,drop=-1,side=0,h=[];const back='LNSGKGSNL'.split('');
function init(){a=Array(81).fill('');back.forEach((x,i)=>{a[i]=x.toLowerCase();a[72+i]=x});for(let i=0;i<9;i++){a[18+i]='p';a[54+i]='P'}a[10]='b';a[16]='r';a[64]='R';a[70]='B';side=0;h=[];draw()}
function own(p){return p&&((side===0)===(p===p.toUpperCase()))}
function moveTo(i){if(side)return;if(drop>=0&&!a[i]){a[i]=h.splice(drop,1)[0];drop=-1;end();return}if(sel>=0&&ok(i)){let p=a[sel],cap=a[i],rank=i/9|0;a[i]=p;a[sel]='';sel=-1;if(cap)h.push(cap.toUpperCase());if(pr[p]&&rank<=2){let force=(p==='P'||p==='L')&&rank===0||p==='N'&&rank<=1;if(force||confirm('Promote this unit?'))a[i]=pr[p]}end();return}if(own(a[i])){sel=i;drop=-1;draw()}}
function ok(i){if(sel<0||a[i]&&own(a[i]))return false;let p=a[sel].toUpperCase(),x=sel%9,y=sel/9|0,X=i%9,Y=i/9|0,dx=X-x,dy=Y-y,s=side?1:-1;if(p==='P'||p==='L')return dx===0&&dy===s;if(p==='N')return Math.abs(dx)===1&&dy===2*s;if('KGS'.includes(p))return Math.abs(dx)<=1&&Math.abs(dy)<=1;return p==='B'?Math.abs(dx)===Math.abs(dy):p==='R'&&(dx===0||dy===0)}
function draw(){bd.innerHTML='';a.forEach((p,i)=>{let e=document.createElement('div');e.className='cell '+(sel===i?'pick':'')+(sel>=0&&ok(i)?' can':'');e.onclick=()=>moveTo(i);if(p){let u=document.createElement('div'),t=p.toUpperCase(),r=rows[t];u.className='unit '+(p===t?'':'blue');u.style.backgroundImage=`url(${p===t?'./shogi-player.png':'./shogi-enemy.png'})`;u.style.backgroundSize='100% 1100%';u.style.backgroundPosition=`0 ${r/10*100}%`;let tag=document.createElement('span');tag.className='pieceTag '+(p===t?'':'enemy')+(['K','G','S'].includes(t)?' key':'');tag.textContent=name[t];e.title=(p===t?'自軍 ':'敵軍 ')+name[t];e.append(u,tag)}bd.append(e)});tr.innerHTML='';h.forEach((p,i)=>{let b=document.createElement('button');b.className='buy';b.textContent=p;b.onclick=()=>{drop=i;sel=-1;g.textContent='Choose an empty square.';draw()};tr.append(b)});st.textContent=side?'Computer turn':'Your turn'}
function end(){side=1;draw();g.textContent='Computer is thinking...';setTimeout(ai,550)}
function ai(){let z=[];a.forEach((p,i)=>{if(p&&p===p.toLowerCase())for(let j=0;j<81;j++){let o=sel;sel=i;if(ok(j))z.push([i,j]);sel=o}});if(z[0]){let[x,y]=z.find(v=>a[v[1]])||z[0];a[y]=a[x];a[x]=''}side=0;draw();g.textContent='Your turn.'}init()
})();
